apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }} # Dynamic image reference
        ports:
        - containerPort: 80