name: CI/CD Pipeline for NGINX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ensure this is lowercase
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          my_nginx=nginx:${{ github.run_number }}
          docker build -t $my_nginx .
          docker tag $my_nginx ${{ secrets.DOCKER_USERNAME }}/$my_nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/$my_nginx
          echo "::set-output name=image::$my_nginx"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create .kube and .minikube directories
        run: |
          mkdir -p $HOME/.kube
          mkdir -p $HOME/.minikube/profiles/minikube/

      - name: Set up KUBECONFIG and Certificates
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          echo "${{ secrets.CLIENT_CRT }}" > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.CLIENT_KEY }}" > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.CA_CRT }}" > $HOME/.minikube/profiles/minikube/ca.crt

      - name: List files in .minikube directory
        run: |
          echo "Contents of $HOME/.minikube/profiles/minikube:"
          ls -l $HOME/.minikube/profiles/minikube/

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/nginx-deployment nginx=${{ secrets.DOCKER_USERNAME }}/${{ needs.build.outputs.image }}

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f k8s/nginx-service.yaml